### ISSUE TITLE
passive skill data is out of date 

### ISSUE THREAD

**Issue by Liberatorist** [majorregal/TimelessEmulator#1]
3.20 added a new curse wheel around "Steeped in the Profane", which is not included in Content/data/passive_skills.json yet.
On that occasion I'd also like to ask you where you're fetching all the data in Content/data from. 
I tried adding the missing passives myself, but I don't know where to get the values in the "Stats" field from.

**Comment by majorregal** [comment]
You can export those files using this web tool: https://snosme.github.io/poe-dat-viewer/
